service: user-service

provider:
  name: aws
  runtime: nodejs20.x

functions:
  signup:
    handler: app/handler.Signup
    events:
      - httpApi:
          path: /signup
          method: get
 
plugins:
  - serverless-offline

custom:
  esbuild:
    enabled: false
